# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: tour
    weight: 10
  - name: Protocols
    url: post
    weight: 20
  - name: Data
    url: data
    weight: 30
  - name: Publications
    url: publication
    weight: 40
  - name: FAQ
    url: faq
    weight: 50
  - name: Starter Kits
    url: kits
    weight: 60
  - name: Tools
    identifier: tools
    weight: 65
  - name: ProbeMaker
    parent: tools
    url: probe-maker
    weight: 10
  - name: Seed Finder
    parent: tools
    url: seed-finder
    weight: 20
  - name: Seed Hit Browser
    parent: tools
    url: seed-hit-browser
    weight: 30
  - name: Flex v2 Cost Calculator
    parent: tools
    url: flex-v2-cost-calculator
    weight: 40
  - name: Contact
    url: contact
    weight: 70
